version: "3.8"

services:
  {{.Name}}:
    image: {{.Name}}:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        GO_VERSION: $GO_VERSION
        GOLANGCI_LINT_VERSION: $GOLANGCI_LINT_VERSION
    volumes:
      - .:/app/src
    command: go run ./cmd/{{.Name}}
